# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhCWUfWceuvuBSEQN5mxxWChKWKcEEVp
"""



"""# Task
The user wants to design data models for a 'HARVESTER TECHNICIAN PERFORMANCE TRACKING APP'. This involves defining various data structures for user authentication, attendance tracking, home dashboard KPIs, different types of visit data (Dealership Visit, Customer Complaint / Service, Pre-Season Readiness, Retrofitment, Installation, PDI, Others), and finally outlining database schema recommendations based on these models. The goal is to create a comprehensive blueprint for frontend UI and backend API development.

## Define User and Authentication Data Model

### Subtask:
Create Python classes or Pydantic models to represent user profiles (Employee ID, Name, State, Region, Designation) and the login process (Mobile Number, OTP verification), which will be essential for the LOGIN MODULE.

**Reasoning**:
Define the `UserProfile` dataclass as specified in the instructions, including Employee ID, Name, State, Region, and Designation.
"""

from dataclasses import dataclass

@dataclass
class UserProfile:
    employee_id: str
    name: str
    state: str
    region: str
    designation: str

print("UserProfile dataclass defined.")

"""**Reasoning**:
Define a dataclass for login credentials to handle mobile number and OTP verification.


"""

from dataclasses import dataclass

@dataclass
class LoginCredentials:
    mobile_number: str
    otp: str

print("LoginCredentials dataclass defined.")

"""## Define Attendance Data Model

### Subtask:
Develop a Python data structure to capture and store attendance details, including auto-captured date, time, GPS coordinates (latitude, longitude), and location address for both check-in and check-out, as specified in the ATTENDANCE MODULE.

**Reasoning**:
Create the `AttendanceRecord` dataclass with all the specified fields and their respective type hints to capture attendance details.
"""

from dataclasses import dataclass
from datetime import date, time

@dataclass
class AttendanceRecord:
    employee_id: str
    check_in_date: date
    check_in_time: time
    check_in_latitude: float
    check_in_longitude: float
    check_in_address: str
    check_out_date: date
    check_out_time: time
    check_out_latitude: float
    check_out_longitude: float
    check_out_address: str

print("AttendanceRecord dataclass defined.")

"""## Define Home Dashboard KPI Data Model

### Subtask:
Create Python data structures to represent the various Key Performance Indicator (KPI) cards displayed on the HOME DASHBOARD, such as Attendance Status, Visits Completed, Visit Target, Productivity %, Hours Logged, Complaint Closed, and Dealer Visits.

**Reasoning**:
Define the `HomeDashboardKPIs` dataclass with all the specified fields and their respective type hints to represent the home dashboard KPIs.
"""

from dataclasses import dataclass

@dataclass
class HomeDashboardKPIs:
    attendance_status: str  # e.g., "Present", "Absent", "Leave"
    visits_completed: int
    visit_target: int
    productivity_percentage: float
    hours_logged: float
    complaints_closed: int
    dealer_visits: int

print("HomeDashboardKPIs dataclass defined.")

"""## Define Visit Type Enumeration

### Subtask:
Implement a Python Enum or similar structure to define the different types of visits specified under ADD NEW VISIT (Dealership Visit, Customer Complaint / Service, Pre-Season Readiness, Retrofitment, Installation, PDI, Others).

**Reasoning**:
Define the `VisitType` enum using the `enum` module to list all specified visit types.
"""

from enum import Enum

class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

print("VisitType Enum defined.")

"""## Design Base Visit Data Model

### Subtask:
Create a foundational Python data model for a generic visit, including common fields like auto-populated date, auto-captured GPS, and a field for the visit type, which all specific visit types will extend or reference.

**Reasoning**:
Define the `BaseVisit` dataclass as specified, incorporating fields for employee ID, auto-populated date and time, auto-captured GPS coordinates, and the `VisitType` enum to categorize the visit.
"""

from dataclasses import dataclass
from datetime import date, time
from enum import Enum

# Assuming VisitType Enum is already defined in a previous cell
# If not, it should be re-defined or imported from a common module

# Re-defining VisitType for clarity if this cell runs independently
class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

print("BaseVisit dataclass defined.")

"""## Design Dealership Visit Data Model

### Subtask:
Develop a specific Python data model for 'Dealership Visit' incorporating fields like State, Dealer Code, Dealer Name (with an indication for fetching from a backend master table), Remarks, and Visit Photo Upload, along with auto-captured GPS, Date, and Time as per the DEALERSHIP VISIT SCREEN.

**Reasoning**:
Define the `DealershipVisit` dataclass that inherits from `BaseVisit` and includes the specific fields for state, dealer code, dealer name, remarks, and visit photo upload.
"""

from dataclasses import dataclass
from typing import List

# Assuming BaseVisit and VisitType are defined in previous cells
# If not, they should be re-defined or imported from a common module

# Re-defining VisitType and BaseVisit for clarity if this cell runs independently
from datetime import date, time
from enum import Enum

class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

@dataclass
class DealershipVisit(BaseVisit):
    state: str
    dealer_code: str
    dealer_name: str
    remarks: str
    visit_photo_upload: List[str] # List of URLs or paths to photos

    def __post_init__(self):
        if self.visit_type != VisitType.DEALERSHIP_VISIT:
            raise ValueError("Visit type must be DEALERSHIP_VISIT for DealershipVisit")

print("DealershipVisit dataclass defined.")

"""## Design Customer Complaint Data Model

### Subtask:
Define a Python data model for 'Customer Complaint' visits, including Complaint Type, Customer Name, Contact Number, Machine Chassis Number, Hour Meter Reading, Co Assistant 1 & 2, specific photo uploads (Chassis Number Photo, Hour Meter Photo, Machine Photo) with auto geo-tagging, Complaint Description, and Corrective Action Taken, as detailed in the CUSTOMER COMPLAINT SCREEN.

**Reasoning**:
Define the `CustomerComplaintVisit` dataclass with all the specified fields, inheriting from `BaseVisit`, and include the `__post_init__` method to enforce the correct visit type.
"""

from dataclasses import dataclass
from typing import List, Optional
from datetime import date, time
from enum import Enum

# Re-defining VisitType and BaseVisit for clarity if this cell runs independently
class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

@dataclass
class CustomerComplaintVisit(BaseVisit):
    complaint_type: str
    customer_name: str
    contact_number: str
    machine_chassis_number: str
    hour_meter_reading: float
    co_assistant_1: Optional[str] = None  # Optional field
    co_assistant_2: Optional[str] = None  # Optional field
    chassis_number_photo: List[str] # List of URLs or paths to photos
    hour_meter_photo: List[str] # List of URLs or paths to photos
    machine_photo: List[str] # List of URLs or paths to photos
    complaint_description: str
    corrective_action_taken: str

    def __post_init__(self):
        if self.visit_type != VisitType.CUSTOMER_COMPLAINT_SERVICE:
            raise ValueError("Visit type must be CUSTOMER_COMPLAINT_SERVICE for CustomerComplaintVisit")

print("CustomerComplaintVisit dataclass defined.")

"""**Reasoning**:
To resolve the `TypeError`, I need to reorder the fields in the `CustomerComplaintVisit` dataclass, ensuring that all non-default arguments (required fields) come before any default arguments (optional fields).


"""

from dataclasses import dataclass
from typing import List, Optional
from datetime import date, time
from enum import Enum

# Re-defining VisitType and BaseVisit for clarity if this cell runs independently
class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

@dataclass
class CustomerComplaintVisit(BaseVisit):
    complaint_type: str
    customer_name: str
    contact_number: str
    machine_chassis_number: str
    hour_meter_reading: float
    chassis_number_photo: List[str] # List of URLs or paths to photos
    hour_meter_photo: List[str] # List of URLs or paths to photos
    machine_photo: List[str] # List of URLs or paths to photos
    complaint_description: str
    corrective_action_taken: str
    co_assistant_1: Optional[str] = None  # Optional field, moved to end
    co_assistant_2: Optional[str] = None  # Optional field, moved to end

    def __post_init__(self):
        if self.visit_type != VisitType.CUSTOMER_COMPLAINT_SERVICE:
            raise ValueError("Visit type must be CUSTOMER_COMPLAINT_SERVICE for CustomerComplaintVisit")

print("CustomerComplaintVisit dataclass defined.")

"""## Design Pre-Season Readiness Data Model

### Subtask:
Create a Python data model for 'Pre-Season Readiness' visits, including Customer Name, Contact Number, Chassis Number, photo uploads (Hour Meter Photo, Machine Photo), and auto-captured GPS, based on the PRE SEASON READINESS SCREEN specifications.

**Reasoning**:
Define the `PreSeasonReadinessVisit` dataclass with all specified fields and inherit from `BaseVisit`.
"""

from dataclasses import dataclass
from typing import List
from datetime import date, time
from enum import Enum

# Re-defining VisitType and BaseVisit for clarity if this cell runs independently
class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

@dataclass
class PreSeasonReadinessVisit(BaseVisit):
    customer_name: str
    contact_number: str
    chassis_number: str
    hour_meter_photo: List[str] # List of URLs or paths to photos
    machine_photo: List[str] # List of URLs or paths to photos

    def __post_init__(self):
        if self.visit_type != VisitType.PRE_SEASON_READINESS:
            raise ValueError("Visit type must be PRE_SEASON_READINESS for PreSeasonReadinessVisit")

print("PreSeasonReadinessVisit dataclass defined.")

"""## Design Retrofitment Data Model

### Subtask:
Develop a Python data model for 'Retrofitment' visits, including Customer Name, Contact Number, Machine Chassis Number, and photo uploads (Hour Meter Photo, Retrofitment Work Photo) with auto geo-tagging, aligning with the RETROFITMENT SCREEN.

**Reasoning**:
Define the `RetrofitmentVisit` dataclass with all specified fields, inheriting from `BaseVisit`, and include the `__post_init__` method to enforce the correct visit type.
"""

from dataclasses import dataclass
from typing import List
from datetime import date, time
from enum import Enum

# Re-defining VisitType and BaseVisit for clarity if this cell runs independently
class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

@dataclass
class RetrofitmentVisit(BaseVisit):
    customer_name: str
    contact_number: str
    machine_chassis_number: str
    hour_meter_photo: List[str] # List of URLs or paths to photos
    retrofitment_work_photo: List[str] # List of URLs or paths to photos

    def __post_init__(self):
        if self.visit_type != VisitType.RETROFITMENT:
            raise ValueError("Visit type must be RETROFITMENT for RetrofitmentVisit")

print("RetrofitmentVisit dataclass defined.")

"""## Design Installation Data Model

### Subtask:
Define a Python data model for 'Installation' visits, including Customer Name, Contact Number, Machine Chassis Number, and photo uploads (Installation Photo, Hour Meter Photo) with auto-captured GPS, as per the INSTALLATION SCREEN.

**Reasoning**:
Define the `InstallationVisit` dataclass with all specified fields, inheriting from `BaseVisit`, and include the `__post_init__` method to enforce the correct visit type, as per the instructions.
"""

from dataclasses import dataclass
from typing import List
from datetime import date, time
from enum import Enum

# Re-defining VisitType and BaseVisit for clarity if this cell runs independently
class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

@dataclass
class InstallationVisit(BaseVisit):
    customer_name: str
    contact_number: str
    machine_chassis_number: str
    installation_photo: List[str] # List of URLs or paths to photos
    hour_meter_photo: List[str] # List of URLs or paths to photos

    def __post_init__(self):
        if self.visit_type != VisitType.INSTALLATION:
            raise ValueError("Visit type must be INSTALLATION for InstallationVisit")

print("InstallationVisit dataclass defined.")

"""## Design PDI Data Model

### Subtask:
Create a Python data model for 'PDI' visits, including Dealer Name, Machine Chassis Number, and photo uploads (Chassis Number Photo, Hour Meter Photo, Machine Photos) with auto-captured GPS, based on the PDI SCREEN details.

**Reasoning**:
Define the `PDIVisit` dataclass as specified, including all required fields and the validation in `__post_init__`.
"""

from dataclasses import dataclass
from typing import List
from datetime import date, time
from enum import Enum

# Re-defining VisitType and BaseVisit for clarity if this cell runs independently
class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

@dataclass
class PDIVisit(BaseVisit):
    dealer_name: str
    machine_chassis_number: str
    chassis_number_photo: List[str] # List of URLs or paths to photos
    hour_meter_photo: List[str] # List of URLs or paths to photos
    machine_photos: List[str] # List of URLs or paths to photos

    def __post_init__(self):
        if self.visit_type != VisitType.PDI:
            raise ValueError("Visit type must be PDI for PDIVisit")

print("PDIVisit dataclass defined.")

"""## Design Others Visit Data Model

### Subtask:
Develop a Python data model for 'Others' visits, including fields for Reason and Remarks, as described in the OTHERS SCREEN.

**Reasoning**:
Define the `OthersVisit` dataclass with the specified fields and `__post_init__` method for validation.
"""

from dataclasses import dataclass
from typing import List
from datetime import date, time
from enum import Enum

# Re-defining VisitType and BaseVisit for clarity if this cell runs independently
class VisitType(Enum):
    DEALERSHIP_VISIT = "Dealership Visit"
    CUSTOMER_COMPLAINT_SERVICE = "Customer Complaint / Service"
    PRE_SEASON_READINESS = "Pre-Season Readiness"
    RETROFITMENT = "Retrofitment"
    INSTALLATION = "Installation"
    PDI = "PDI"
    OTHERS = "Others"

@dataclass
class BaseVisit:
    employee_id: str
    visit_date: date
    visit_time: time
    latitude: float
    longitude: float
    visit_type: VisitType

@dataclass
class OthersVisit(BaseVisit):
    reason: str
    remarks: str

    def __post_init__(self):
        if self.visit_type != VisitType.OTHERS:
            raise ValueError("Visit type must be OTHERS for OthersVisit")

print("OthersVisit dataclass defined.")

"""## Outline Database Schema Recommendations

### Subtask:
Provide recommendations for a conceptual database schema (e.g., SQL tables or NoSQL collections) based on all the defined Python data models, ensuring proper relationships and data persistence for the application.

```markdown
### Database Schema Recommendations

Based on the defined Python data models, here are the recommendations for a conceptual SQL database schema. The focus is on ensuring proper relationships and data persistence.

---

#### 1. `UserProfile` Model -> `users` Table

This table will store the core information for each technician.

-   **Table Name**: `users`
-   **Columns**:
    -   `employee_id` (VARCHAR(50) PRIMARY KEY): Unique identifier for the employee.
    -   `name` (VARCHAR(100) NOT NULL): Full name of the employee.
    -   `state` (VARCHAR(50) NOT NULL): State where the employee operates.
    -   `region` (VARCHAR(50) NOT NULL): Region where the employee operates.
    -   `designation` (VARCHAR(50) NOT NULL): Employee's designation (e.g., 'Technician', 'Manager').
-   **Relationships**: None directly with this table yet, but `employee_id` will be a foreign key in other tables.
-   **Indexes**: Index on `employee_id` (already primary key).

---

#### 2. `LoginCredentials` Model -> `login_credentials` Table

This table will handle authentication details, potentially linked to the `users` table.

-   **Table Name**: `login_credentials`
-   **Columns**:
    -   `employee_id` (VARCHAR(50) PRIMARY KEY): Foreign Key referencing `users.employee_id`.
    -   `mobile_number` (VARCHAR(15) UNIQUE NOT NULL): Employee's mobile number, used for login.
    -   `otp_hash` (VARCHAR(255) NOT NULL): Hashed One-Time Password for verification. (Store hash, not raw OTP).
    -   `otp_created_at` (DATETIME NOT NULL): Timestamp when the OTP was generated.
-   **Relationships**:
    -   `employee_id` (FK) -> `users.employee_id` (One-to-one relationship).
-   **Indexes**: Index on `mobile_number` for quick lookups during login.
```

```markdown
#### 3. `AttendanceRecord` Model -> `attendance_records` Table

This table will store the daily attendance details for each technician.

-   **Table Name**: `attendance_records`
-   **Columns**:
    -   `attendance_id` (INT PRIMARY KEY AUTO_INCREMENT): Unique identifier for each attendance record.
    -   `employee_id` (VARCHAR(50) NOT NULL): Foreign Key referencing `users.employee_id`.
    -   `check_in_date` (DATE NOT NULL): Date of check-in.
    -   `check_in_time` (TIME NOT NULL): Time of check-in.
    -   `check_in_latitude` (DECIMAL(10, 8) NOT NULL): Latitude at check-in.
    -   `check_in_longitude` (DECIMAL(11, 8) NOT NULL): Longitude at check-in.
    -   `check_in_address` (VARCHAR(255) NOT NULL): Address at check-in.
    -   `check_out_date` (DATE): Date of check-out (can be NULL if not checked out yet).
    -   `check_out_time` (TIME): Time of check-out (can be NULL).
    -   `check_out_latitude` (DECIMAL(10, 8)): Latitude at check-out (can be NULL).
    -   `check_out_longitude` (DECIMAL(11, 8)): Longitude at check-out (can be NULL).
    -   `check_out_address` (VARCHAR(255)): Address at check-out (can be NULL).
-   **Relationships**:
    -   `employee_id` (FK) -> `users.employee_id` (Many-to-one relationship, an employee can have many attendance records).
-   **Indexes**: Index on `employee_id`, and a compound index on `employee_id` and `check_in_date` for efficient queries.

---
```

```markdown
#### 4. `HomeDashboardKPIs` Model -> Derived Metrics

The `HomeDashboardKPIs` are aggregate metrics that would typically be **derived** from the data stored in other tables (e.g., `attendance_records`, `visits`, `customer_complaint_visits`). They are not usually stored as a standalone table in a transactional database. Instead, they would be calculated on demand or pre-calculated and cached for performance, perhaps in a separate analytics or reporting layer.

---

#### 5. `VisitType` Enum -> `visit_types` Lookup Table

This table will store the predefined types of visits as a lookup reference, ensuring consistency across all visit records.

-   **Table Name**: `visit_types`
-   **Columns**:
    -   `id` (INT PRIMARY KEY AUTO_INCREMENT): Unique identifier for each visit type.
    -   `type_name` (VARCHAR(100) UNIQUE NOT NULL): The descriptive name of the visit type (e.g., 'Dealership Visit').
-   **Relationships**: `id` will be a foreign key in the main `visits` table.
-   **Indexes**: Index on `type_name` for efficient lookups.

---

#### 6. `BaseVisit` Model -> `visits` Table

This central table will store the common information for all types of visits, acting as a parent table for specific visit detail tables.

-   **Table Name**: `visits`
-   **Columns**:
    -   `visit_id` (INT PRIMARY KEY AUTO_INCREMENT): Unique identifier for each visit.
    -   `employee_id` (VARCHAR(50) NOT NULL): Foreign Key referencing `users.employee_id`.
    -   `visit_date` (DATE NOT NULL): Date of the visit.
    -   `visit_time` (TIME NOT NULL): Time of the visit.
    -   `latitude` (DECIMAL(10, 8) NOT NULL): Latitude at the time of visit.
    -   `longitude` (DECIMAL(11, 8) NOT NULL): Longitude at the time of visit.
    -   `visit_type_id` (INT NOT NULL): Foreign Key referencing `visit_types.id`.
-   **Relationships**:
    -   `employee_id` (FK) -> `users.employee_id` (Many-to-one relationship).
    -   `visit_type_id` (FK) -> `visit_types.id` (Many-to-one relationship).
-   **Indexes**: Index on `employee_id`, `visit_date`, and `visit_type_id` for efficient filtering and joining.

---
```

```markdown
#### 7. `DealershipVisit` Model -> `dealership_visits` Table

This table will store the specific details for dealership visits.

-   **Table Name**: `dealership_visits`
-   **Columns**:
    -   `visit_id` (INT PRIMARY KEY): Foreign Key referencing `visits.visit_id`.
    -   `state` (VARCHAR(50) NOT NULL): State where the dealership is located.
    -   `dealer_code` (VARCHAR(50) NOT NULL): Unique code for the dealer.
    -   `dealer_name` (VARCHAR(100) NOT NULL): Name of the dealer.
    -   `remarks` (TEXT): Any additional remarks about the visit.
    -   `visit_photo_upload_urls` (TEXT): A JSON string or delimited string storing URLs/paths to visit photos.
-   **Relationships**:
    -   `visit_id` (FK) -> `visits.visit_id` (One-to-one relationship, as this is an extension of a `BaseVisit`).
-   **Indexes**: Index on `dealer_code` for efficient lookups.

---
```

```markdown
#### 8. `CustomerComplaintVisit` Model -> `customer_complaint_visits` Table

This table will store the specific details for customer complaint/service visits.

-   **Table Name**: `customer_complaint_visits`
-   **Columns**:
    -   `visit_id` (INT PRIMARY KEY): Foreign Key referencing `visits.visit_id`.
    -   `complaint_type` (VARCHAR(100) NOT NULL): Type of complaint.
    -   `customer_name` (VARCHAR(100) NOT NULL): Name of the customer.
    -   `contact_number` (VARCHAR(20) NOT NULL): Customer's contact number.
    -   `machine_chassis_number` (VARCHAR(50) NOT NULL): Chassis number of the machine.
    -   `hour_meter_reading` (DECIMAL(10, 2) NOT NULL): Hour meter reading at the time of visit.
    -   `co_assistant_1` (VARCHAR(100)): Name of the first co-assistant (nullable).
    -   `co_assistant_2` (VARCHAR(100)): Name of the second co-assistant (nullable).
    -   `chassis_number_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for chassis number photos.
    -   `hour_meter_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for hour meter photos.
    -   `machine_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for machine photos.
    -   `complaint_description` (TEXT NOT NULL): Detailed description of the complaint.
    -   `corrective_action_taken` (TEXT NOT NULL): Description of the corrective action taken.
-   **Relationships**:
    -   `visit_id` (FK) -> `visits.visit_id` (One-to-one relationship, as this is an extension of a `BaseVisit`).
-   **Indexes**: Index on `machine_chassis_number` for quick lookups.

---
```

```markdown
#### 9. `PreSeasonReadinessVisit` Model -> `pre_season_readiness_visits` Table

This table will store the specific details for pre-season readiness visits.

-   **Table Name**: `pre_season_readiness_visits`
-   **Columns**:
    -   `visit_id` (INT PRIMARY KEY): Foreign Key referencing `visits.visit_id`.
    -   `customer_name` (VARCHAR(100) NOT NULL): Name of the customer.
    -   `contact_number` (VARCHAR(20) NOT NULL): Customer's contact number.
    -   `chassis_number` (VARCHAR(50) NOT NULL): Chassis number of the machine.
    -   `hour_meter_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for hour meter photos.
    -   `machine_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for machine photos.
-   **Relationships**:
    -   `visit_id` (FK) -> `visits.visit_id` (One-to-one relationship, as this is an extension of a `BaseVisit`).
-   **Indexes**: Index on `chassis_number`.

---
```

```markdown
#### 10. `RetrofitmentVisit` Model -> `retrofitment_visits` Table

This table will store the specific details for retrofitment visits.

-   **Table Name**: `retrofitment_visits`
-   **Columns**:
    -   `visit_id` (INT PRIMARY KEY): Foreign Key referencing `visits.visit_id`.
    -   `customer_name` (VARCHAR(100) NOT NULL): Name of the customer.
    -   `contact_number` (VARCHAR(20) NOT NULL): Customer's contact number.
    -   `machine_chassis_number` (VARCHAR(50) NOT NULL): Chassis number of the machine.
    -   `hour_meter_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for hour meter photos.
    -   `retrofitment_work_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for retrofitment work photos.
-   **Relationships**:
    -   `visit_id` (FK) -> `visits.visit_id` (One-to-one relationship, as this is an extension of a `BaseVisit`).
-   **Indexes**: Index on `machine_chassis_number`.

---
```

```markdown
#### 11. `InstallationVisit` Model -> `installation_visits` Table

This table will store the specific details for installation visits.

-   **Table Name**: `installation_visits`
-   **Columns**:
    -   `visit_id` (INT PRIMARY KEY): Foreign Key referencing `visits.visit_id`.
    -   `customer_name` (VARCHAR(100) NOT NULL): Name of the customer.
    -   `contact_number` (VARCHAR(20) NOT NULL): Customer's contact number.
    -   `machine_chassis_number` (VARCHAR(50) NOT NULL): Chassis number of the machine.
    -   `installation_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for installation photos.
    -   `hour_meter_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for hour meter photos.
-   **Relationships**:
    -   `visit_id` (FK) -> `visits.visit_id` (One-to-one relationship, as this is an extension of a `BaseVisit`).
-   **Indexes**: Index on `machine_chassis_number`.

---
```

```markdown
#### 12. `PDIVisit` Model -> `pdi_visits` Table

This table will store the specific details for PDI visits.

-   **Table Name**: `pdi_visits`
-   **Columns**:
    -   `visit_id` (INT PRIMARY KEY): Foreign Key referencing `visits.visit_id`.
    -   `dealer_name` (VARCHAR(100) NOT NULL): Name of the dealer.
    -   `machine_chassis_number` (VARCHAR(50) NOT NULL): Chassis number of the machine.
    -   `chassis_number_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for chassis number photos.
    -   `hour_meter_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for hour meter photos.
    -   `machine_photo_urls` (TEXT): JSON string or delimited string of URLs/paths for machine photos.
-   **Relationships**:
    -   `visit_id` (FK) -> `visits.visit_id` (One-to-one relationship, as this is an extension of a `BaseVisit`).
-   **Indexes**: Index on `machine_chassis_number`.

---
```

```markdown
#### 13. `OthersVisit` Model -> `others_visits` Table

This table will store the specific details for 'Others' visits.

-   **Table Name**: `others_visits`
-   **Columns**:
    -   `visit_id` (INT PRIMARY KEY): Foreign Key referencing `visits.visit_id`.
    -   `reason` (VARCHAR(255) NOT NULL): The reason for the 'Other' visit.
    -   `remarks` (TEXT): Any additional remarks about the visit.
-   **Relationships**:
    -   `visit_id` (FK) -> `visits.visit_id` (One-to-one relationship, as this is an extension of a `BaseVisit`).
-   **Indexes**: None specific, as direct lookups are less likely than through `visits`.

---
```

## Final Task

### Subtask:
Provide a summary of the comprehensive data models designed for the 'HARVESTER TECHNICIAN PERFORMANCE TRACKING APP' and discuss how these models form the foundational blueprint for both frontend UI development and backend API implementation.

# Task
The user wants to design data models for a 'HARVESTER TECHNICIAN PERFORMANCE TRACKING APP'. This involves defining various data structures for user authentication, attendance tracking, home dashboard KPIs, different types of visit data (Dealership Visit, Customer Complaint / Service, Pre-Season Readiness, Retrofitment, Installation, PDI, Others), and finally outlining database schema recommendations based on these models. The goal is to create a comprehensive blueprint for frontend UI and backend API development.

# Task
The user wants to design data models for a 'HARVESTER TECHNICIAN PERFORMANCE TRACKING APP'. This involves defining various data structures for user authentication, attendance tracking, home dashboard KPIs, different types of visit data (Dealership Visit, Customer Complaint / Service, Pre-Season Readiness, Retrofitment, Installation, PDI, Others), and finally outlining database schema recommendations based on these models. The goal is to create a comprehensive blueprint for frontend UI and backend API development.

## Final Task

### Subtask:
Provide a summary of the comprehensive data models designed for the 'HARVESTER TECHNICIAN PERFORMANCE TRACKING APP' and discuss how these models form the foundational blueprint for both frontend UI development and backend API implementation.
"""
